version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: registry.ilyasabdut.loseyourip.com/personal-portfolio:latest
    volumes:
      - ./sqlite:/app/sqlite
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
