version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./sqlite:/app/data
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
